name: Gerar Aplicativo CanTudo
on:
  push:
    branches: [ principal, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Dependências e EAS
        run: |
          npm install -g eas-cli
          npm install --legacy-peer-deps

      - name: Compilar APK Android na Nuvem
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
